// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ084x2p3uM5Z3SeogRiTDpIqIPf5g8o8',
    appId: '1:423866012326:web:9e6d94fd24feb2a5cd9a67',
    messagingSenderId: '423866012326',
    projectId: 'news-app-c976f',
    authDomain: 'news-app-c976f.firebaseapp.com',
    storageBucket: 'news-app-c976f.firebasestorage.app',
    measurementId: 'G-LXSY55KY1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0KA3aBE4zAdHNZCNYhrfbh5OGoFPanKM',
    appId: '1:423866012326:android:8c44504fbd1dfc3acd9a67',
    messagingSenderId: '423866012326',
    projectId: 'news-app-c976f',
    storageBucket: 'news-app-c976f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9fRhN7a3OI8XnC3XGaail06VlNKpK8f8',
    appId: '1:423866012326:ios:831351718690a837cd9a67',
    messagingSenderId: '423866012326',
    projectId: 'news-app-c976f',
    storageBucket: 'news-app-c976f.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Qnxw8X75YCYlypJUaMpEsXnd8Sre__E',
    appId: '1:17590632308:ios:f3008651b1ea5764453621',
    messagingSenderId: '17590632308',
    projectId: 'news-app-97d81',
    storageBucket: 'news-app-97d81.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ084x2p3uM5Z3SeogRiTDpIqIPf5g8o8',
    appId: '1:423866012326:web:66915258b1d492d0cd9a67',
    messagingSenderId: '423866012326',
    projectId: 'news-app-c976f',
    authDomain: 'news-app-c976f.firebaseapp.com',
    storageBucket: 'news-app-c976f.firebasestorage.app',
    measurementId: 'G-Z79P798J94',
  );

}